# Generated by Django 5.1.5 on 2025-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
